DROP TABLE IF EXISTS recipe, ingredient;

CREATE TABLE recipe
(
    id                             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                           varchar(250),
    description                    varchar(1000),
    image__urls                    varchar(250)
);

CREATE TABLE ingredient
(
    id                             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                           varchar(200) NOT NULL,
    recipe__id                     INT NOT NULL,

    CONSTRAINT fk__ab__recipe FOREIGN KEY (recipe__id) REFERENCES recipe (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT into recipe(name, description, image__urls) VALUES
('Brisket with vegetables in Korean', 'Prepare the food, wash the vegetables, cut the brisket. Heat the vegetable oil in a wide frying pan, grease the entire bottom with it. Fry the brisket until nicely browned, 5-7 minutes, over medium heat. Add the onion feathers and cook for 3 minutes, stirring. Sprinkle with breadcrumbs or starch, fry for another couple of minutes. Add eggplant cubes and garlic slices. Fry for a couple of minutes over medium heat. Zucchini cut into cubes, add, fry for 3-5 minutes. Pour in the soy sauce, honey, sprinkle with paprika, ground black pepper, stir, fry for a couple of minutes, pour in the vinegar, stir and remove from the heat. If desired, add salt to your taste. Traditionally served with boiled unleavened rice and a spicy Korean snack.', '1PTdBAnpWL4MdPCshiez9XiyMmaWZeChA'),
('Pork Medallions', 'Wash the pork tenderloin, dry it with a paper towel and remove excess films and tendons. Cut across the fibers into portions, 4-5 cm thick. In the middle of each piece, make an incision to make a \"pocket\" in which to put a cube of cheese. Wrap with a strip of bacon and fasten with a toothpick to preserve the shape of the medallions. Fry in vegetable oil for 2 minutes on both sides. Add salt and pepper to taste.. Put it in a heat-resistant form and send it to the oven at a temperature of 190 ° C for 10 minutes. Let the finished medallions rest for 5 minutes, cut into 2 pieces or serve whole.', '15zDt3WjwdvJIvqbAdeeLR15zvXNi97l_'),
('Chicken and potatoes', 'Wash the ham and dry it. Peel the onion.Fry the ham on both sides in vegetable oil until golden brown, 5-7 minutes, medium heat.\n Add the onion feathers, fry for 3 minutes, medium heat.Add paprika, pepper, lemon slices, and cook over low heat for 5 minutes.Add salt and simmer for 5 minutes.Add the potato slices, cover with a lid, bring to a boil over low heat, and mix gently.', '125YEF0erpXQe1IMigyWnW7lzaG1pgepq');

INSERT into ingredient(name, recipe__id) VALUES
('Chicken', 3),
('Potato', 3), ('Onion', 3), ('Sweet paprika', 3), ('Black pepper', 3), ('Lemon', 3), ('Salt', 3) ,('Vegetable oil', 3);

INSERT into ingredient(name, recipe__id) VALUES
('Brisket (pork)', 1), ('Eggplant', 1), ('Zucchini', 1), ('Onion', 1), ('Garlic (large)',1 ), ('Breadcrumbs', 1),
('Honey', 1), ('Sweet paprika', 1), ('Vinegar', 1), ('Black pepper', 1), ('Soy sauce', 1), ('Vegetable oil', 1);

INSERT into ingredient(name, recipe__id) VALUES
('Pork', 2), ('Bacon', 2), ('Mozzarella', 2), ('Salt', 2), ('Black pepper', 2);
